<a href="https://colab.research.google.com/github/webster4live/planets/blob/main/code_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tensorflow==1.15.0 tensorflow.gpu==1.15.0 stable_baselines gym box2d.py 

  Using cached tensorflow-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl (412.3 MB)
  Using cached tensorflow_gpu-1.15.0-cp37-cp37m-manylinux2010_x86_64.whl (411.5 MB)
  Using cached stable_baselines-2.10.2-py3-none-any.whl (240 kB)
     |████████████████████████████████| 448 kB 15.3 MB/s 
     |████████████████████████████████| 503 kB 53.8 MB/s 
     |████████████████████████████████| 50 kB 6.7 MB/s 
     |████████████████████████████████| 3.8 MB 54.9 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=ce7787a35e3d73c338923cc50171d97a6e86d55ababdd328d3654917e4d07407
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.6.0
    Uninstalling tensorflow-estimator-2.6.0:
      Successfully uninstalled tensorflow-estimator-2.6.0
  Attempting uninstall: tensorboard
    Found existing in

In [ ]:
import gym
from stable_baselines import ACER
from stable_baselines.common.vec_env import DummyVecEnv
from stable_baselines.common.evaluation import evaluate_policy


ModuleNotFoundError: ignored

In [ ]:
|environment_name = 'LunarLander-v2'

In [ ]:
env=gym.make(environment_name)

NameError: ignored

In [ ]:
[1,2,3]

[1, 2, 3]

In [ ]:
my_list=['a','b','c']

In [ ]:
my_list[1]

'b'

In [ ]:
my_list[:]

['a', 'b', 'c']

In [ ]:
my_list[2:]

['c']

In [ ]:
my_list[:2]

['a', 'b']

In [ ]:
my_list.append('d')

In [ ]:
my_list

['a', 'b', 'c', 'd']

In [ ]:
my_list.append('d' 'e')

In [ ]:
my_list

['a', 'b', 'c', 'd', 'de']

In [ ]:
my_list.pop(2)

'c'

In [ ]:
my_list

['a', 'b', 'd', 'de']

In [ ]:
my_list.remove('a')

In [ ]:
my_list

['b', 'd', 'de']

In [ ]:
my_list.push('s')

AttributeError: ignored

In [ ]:
my_list.append('j')

In [ ]:
my_list

['b', 'd', 'de', 'j']

In [ ]:
my_list[:3]

['b', 'd', 'de']

In [ ]:
my_list[3:]

['j']

In [ ]:
my_list[1], my_list[3]='Webster', 'olufunke'

In [ ]:
my_list[1]

'Webster'

In [ ]:
femi = [2,3,5,6,[2,3,5,6],[4,6,6,7,8],[1,2,5,6,7]]

In [ ]:
femi[2]

5

In [ ]:
femi[:]

[2, 3, 5, 6, [2, 3, 5, 6], [4, 6, 6, 7, 8], [1, 2, 5, 6, 7]]

In [ ]:
femi[:7]

[2, 3, 5, 6, [2, 3, 5, 6], [4, 6, 6, 7, 8], [1, 2, 5, 6, 7]]

In [ ]:
femi[:6]

[2, 3, 5, 6, [2, 3, 5, 6], [4, 6, 6, 7, 8]]

In [ ]:
femi[2:5]

[5, 6, [2, 3, 5, 6]]

In [ ]:
femi[2:4]

[5, 6]

In [ ]:
femi[3:6]

[6, [2, 3, 5, 6], [4, 6, 6, 7, 8]]

In [ ]:
femi[2:5,3:6]


NameError: ignored

In [ ]:
def findMum(x):
    return 'Mum' in x.upper().split()
findMum('Mum is coming home')

False

False

In [ ]:
def findDog(x):
    return 'mum' in x.lower().split().count()
findDog('Is there a mum here?')

True

In [ ]:
def caught_speeding(speed, is_birthday):
    if is_birthday == True:
        if speed =>85:
            print('Your head is not correct')
        elif 65< speed <=80:
            print('You should come home tomorrow')
        else:
            print('time is up')
    else:
        if speed<=60:
            print('No Ticket')
        elif 60<speed<=80:
            print('Small Ticket')
        else:
          print('Nig Ticket')
    pass


In [ ]:
caught_speeding(70, True)

Your head is not correct


In [ ]:
caught_speeding(90, True)

time is up


In [ ]:
def celcius_to_kelvin(temp):
    kelvin = ((temp-32)*(5/9)) + 273.15
    return kelvin
pass

In [ ]:
celcius_to_kelvin(70)

294.26111111111106

In [ ]:
from temp_func import celcius_to_kelvin
print(celcius_to_kelvin(50))

ModuleNotFoundError: ignored

In [ ]:
import numpy as np


In [ ]:
np.array([[1,2],[3,4],[5,6],[7,8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.random.random((4,3,2))

array([[[0.36991197, 0.41726882],
        [0.67457765, 0.70807906],
        [0.61699041, 0.67737092]],

       [[0.37140341, 0.75486729],
        [0.9122088 , 0.60739042],
        [0.70746122, 0.1378936 ]],

       [[0.70885285, 0.17760926],
        [0.33965777, 0.39797237],
        [0.30122798, 0.91228561]],

       [[0.64573715, 0.20989581],
        [0.90123119, 0.49748325],
        [0.85735513, 0.64929961]]])

In [ ]:
grid = np.arange(1,10).reshape((3,3
                                ))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.power(2,3)

8

In [ ]:
np.mod(9.8)

ValueError: ignored

In [ ]:
x=np.arange(4)

In [ ]:
print("x = ", x)
print("x+5=",x+5)

x =  [0 1 2 3]
x+5= [5 6 7 8]


In [ ]:
import pandas as pd

In [ ]:
df.head()

NameError: ignored

In [ ]:
df.dtypes
df.head()
df.head(3)
df.tail()
df.tail(3)
df.iloc[9:14]# used to extract specific rows or columns when using the positions in the table i.e indexing
df1 = df.loc[df["total_rooms"]>100, "median_house_value"]# used to extract specific rows or columns when using the row and column name
df["total_rooms"].mean()
df.["total_rooms"].median()
df.["total_rooms"].value_counts()# detremines the frequency of entry in each variable  item
df.describe()
df.[["total_romms","number_boys","whats_up","winter_period"]].describe() #  displays all the attributes of the siagnal 
df1.head()

In [ ]:
white = pd.read_csv("webster.csv")

In [1]:
import matplotlib.pyplot as plt

white['quality'].plot.hist()
import seaborn as sns
sns.scatterplot(x="alchohol", y="H", data=white)

NameError: ignored

In [3]:
friends = ["webster", "funke","mary"]
for friend in friends:
    print(friend)
print("blast off!")

webster
funke
mary
blast off!


In [26]:
##finding largest number
largest_so_far = -1
x = [2,34,4,6,7,89,90,234, -1,909, 34567, 345]
for i in x:
  if i > largest_so_far:
    largest_so_far= i
  print(largest_so_far, i)
print('largest', largest_so_far)

2 2
34 34
34 4
34 6
34 7
89 89
90 90
234 234
234 -1
909 909
34567 34567
34567 345
largest 34567


In [8]:
##number of count
count =0
print('before', count)
for i in [2,3,4,6,1,8,9,10]:
  count = count + 1
  print(count,i) 
print('After', count)

before 0
1 2
2 3
3 4
4 6
5 1
6 8
7 9
8 10
After 8


In [10]:
##summing in a loop
sum = 0
for i in [2,3,4,5,6,12,3,44]:
  sum = sum + i
  print(i, sum)
print('total_sum', sum)

2 2
3 5
4 9
5 14
6 20
12 32
3 35
44 79
total_sum 79


In [3]:
##summing in a loop
count=0
sum = 0
for i in [2,3,4,5,6,12,3,44]:
  count= count + 1
  sum = sum + i
  print(i, sum)
print('total_sum', sum, 'count', count,'average', sum/count)

2 2
3 5
4 9
5 14
6 20
12 32
3 35
44 79
total_sum 79 count 8 average 9.875


In [6]:
## Filtering in a loop
for i in [23,45,56,78,12,34]:
  if i >50:
    print('large_number', i)
print('After', i)


large_number 56
large_number 78
After 34


In [17]:
##search using a boolean variable

found = False
print('before', found)
for value in [23,45,2,1,46,78,99,99]:
  if value == 99:
    found = True
  else:
    found = False
  print(found, value)

before False
False 23
False 45
False 2
False 1
False 46
False 78
True 99
True 99


In [21]:
found = False
print('before', found)
for value in [23,45,2,1,46,78,99,99]:
  if value == 99:
    found = True
  else:
    found = False
  print(found, value)

before False
False 23
False 45
False 2
False 1
False 46
False 78
True 99
True 99


In [24]:
##smallest number
smallest = None
print( 'before',smallest)
for i in [123, 23, 45,56,76,89,23,56,90]:
  if smallest is  None:
    smallest = i
  elif i < smallest :
    smallest = i
  print(smallest, i)
print('After', smallest)

before None
123 123
23 23
23 45
23 56
23 76
23 89
23 23
23 56
23 90
After 23


In [27]:
##largest umber
largest_so_far = None
print( 'before',largest_so_far)
for i in [123, 23, 45,56,76,89,23,56,90]:
  if largest_so_far is  None: ## is is stronger None
    largest_so_far = i
  elif i > largest_so_far :
    largest_so_far = i
  print(largest_so_far, i)
print('After', largest_so_far)

before None
123 123
123 23
123 45
123 56
123 76
123 89
123 23
123 56
123 90
After 123


In [30]:
##looping through strin
name = 'olufunke'
index = 0
while index < len(name):
  letter = name[index]
  print(index, letter)
  index = index +1 


0 o
1 l
2 u
3 f
4 u
5 n
6 k
7 e


In [31]:
 name = 'olufunke'
 for letter in name:
   print(letter)

o
l
u
f
u
n
k
e
